### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by ZephyrRaine** [ZephyrRaine/ML-Mice#3]
- [x] All agents running => Focus on one agent
- [x] Simulation speed : TimeScale? FixedUpdate frequency? Dynamic inference player parameters?
- [x] Show/Hide different stuff: Trails, Winning overlay stuff in front of areas
- [x] Player control
- [x] Reset

- [ ] Make interactable checkpoints + next buttons
- [ ] Additional infos
- [ ] Fix color buttons time
- [ ] Slow down music
- [ ] Add flee brains????
